# Generated by Django 5.2.3 on 2026-01-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('atendido', 'Atendido')], default='pendiente', max_length=20),
        ),
    ]
