"""
Django settings for lavamatic_tropezon_web project.

Generated by 'django-admin startproject' using Django 5.2.3.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY WARNING: keep the secret key used in production secret!
# En producción conviene usar variable de entorno, pero por ahora lo dejamos.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-*%9s-si5%qvit$s%w!)t0g5uy1*g!m$*_782h-^@uv)zn7d)1w"
)

# DEBUG por variable de entorno (Render)
DEBUG = os.environ.get("DEBUG", "True") == "True"

# Hosts permitidos (Render)
# En local, si DEBUG=True no molesta si está vacío.
ALLOWED_HOSTS = [
    "lavamatic-tropezon-web.onrender.com",
    "www.lavamatic-tropezon-web.onrender.com",
]
if not DEBUG:
    # Ejemplo: "lavamatic-tropezon-web.onrender.com"
    # Si querés varios: "dom1.com,dom2.com"
    ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "webinfo",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise para servir static en producción (Render)
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "lavamatic_tropezon_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lavamatic_tropezon_web.wsgi.application"


# Database
# SQLite ok para demo / prueba. Para producción real, mejor Postgres.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
LANGUAGE_CODE = "es-ar"
TIME_ZONE = "America/Argentina/Buenos_Aires"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = "/static/"

# Carpeta donde collectstatic deja TODO listo para producción
STATIC_ROOT = BASE_DIR / "staticfiles"

# Tus estáticos del proyecto
STATICFILES_DIRS = [
    BASE_DIR / "webinfo" / "static",
]

# WhiteNoise storage (comprime + cache busting)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
